### ISSUE TITLE
ACNA-338 - config can only load .env and .aio files once

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-config#44]
### Expected Behaviour
commands that navigate ( process.chdir ) expect local config files to be loaded from the new cwd

### Actual Behaviour
cwd from where the cli is launched is used for eternity and there is no way to reset local config

#### Sample Code that illustrates the problem
```
process.chdir('./somedir')
// call some cli plugin command that used config
otherCommand.run(['get','somekey'])
```

**Comment by shazron** [comment]
Fixed in the commit above, but I believe that just fixes .env reloading. .aio has always used the latest `cwd` when a new Config object is used (lazy load). 

As long as the Config object has been initialized once via reload(), it will retain the .env and .aio `cwd` location, unless `reload` was called. There is no dynamic detection of `cwd` changing for it to force reload.
